import = ["/home/devansh/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
live_config_reload = true

[debug]
log_level = "Warn"
persistent_logging = true

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 14.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = -1
y = 0

[hints]
alphabet = "asdfghjkl;'"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "Up"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "Down"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mode = "~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "G"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "G"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "SearchCancel"
key = "Slash"
mode = "Search"
mods = "Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 100000

[selection]
save_to_clipboard = true

[window]
decorations_theme_variant = "Dark"
dynamic_padding = true
dynamic_title = false
opacity = 1.0
startup_mode = "Maximized"

[window.padding]
x = 5
y = 0
