alias pp='ps -ef'
#alias cls='clear && tmux clear-history 2> /dev/null'
alias cls='echo "\033c"'
alias batt='cat /sys/class/power_supply/BAT1/capacity'
alias ls='ls -N --human-readable --color=auto'
alias grep='grep --color=always'
alias ym='youtube-dl --extract-audio --audio-format mp3 --output "/home/devansh/Music/%(title)s.%(ext)s"'
alias pacman='pacman --color always'
alias kbg='for x in $(jobs -p); do kill -9 $x; done'
alias python2='python2 -W ignore'
alias python3='python3 -W ignore'
alias echo='echo -e'
alias ll='ls -l'
alias la='ls -la'
alias lt='ls -lt | less'
alias rm='rm -i'
alias cdns='source cdns'
