#!/bin/bash

RESURRECT_DIR=~/.local/share/tmux/resurrect
LAST_FILE=$RESURRECT_DIR/last

last_size=$(du $LAST_FILE | awk '{ print $1 }')
if [[ $last_size -eq 0 ]]; then
  rm -f $LAST_FILE

  VALID_RESURRECT_FILE=$(ls -t1 tmux_resurrect_* | head -n 2 | tail -n 1)
  ln -s $VALID_RESURRECT_FILE $LAST_FILE

  find $RESURRECT_DIR -type f -name 'tmux_resurrect*' -empty -delete $argv
fi

tmux kill-server

tmux list-sessions | cut -d ':' -f 1 | grep "default"
if [[ ! $? -eq 0 ]]; then
  tmux new-session "default"
fi

konsole --fullscreen -e "fish -c 'tmux attach-session -t default'"
